spring.application.name=order-service
server.port=8081

# DataSource configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/orders
spring.datasource.username=user
spring.datasource.password=pass

# JPA / Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Explicitly set dialect to avoid metadata issues
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Force JDBC to use correct timezone
spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Kolkata
spring.datasource.hikari.data-source-properties.options=-c TimeZone=Asia/Kolkata

# ActiveMQ settings
spring.activemq.broker-url=tcp://localhost:61616
spring.activemq.user=admin
spring.activemq.password=admin

spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
